set -x

HF_MODEL_PATH=/weight/Qwen3-30B-A3B
DIST_CKPT_PATH=/weight/Qwen3-30B-A3B-dist

tp=4
pp=2
cp=2
ep=8
etp=1

export CUDA_DEVICE_MAX_CONNECTIONS=1

python3 -m verl.trainer.main_ppo --config-path=config \
    --config-name='ppo_megatron_trainer.yaml'\
    algorithm.adv_estimator=grpo \
    data.train_files=/data/processed_gsm8k/train.parquet \
    data.val_files=/data/processed_gsm8k/test.parquet \
    data.train_batch_size=16 \
    data.max_prompt_length=1024 \
    data.max_response_length=2048 \
    data.filter_overlong_prompts=True \
    data.truncation='left' \
    actor_rollout_ref.model.path=$HF_MODEL_PATH \
    actor_rollout_ref.actor.optim.lr=1e-6 \
    actor_rollout_ref.actor.ppo_mini_batch_size=16 \
    actor_rollout_ref.actor.ppo_micro_batch_size_per_gpu=8 \
    actor_rollout_ref.actor.megatron.pipeline_model_parallel_size=$pp \
    actor_rollout_ref.actor.megatron.tensor_model_parallel_size=$tp \
    actor_rollout_ref.actor.megatron.expert_model_parallel_size=$ep \
    actor_rollout_ref.actor.megatron.use_dist_checkpointing=True \
    actor_rollout_ref.actor.megatron.dist_checkpointing_path=$DIST_CKPT_PATH \
    actor_rollout_ref.actor.use_kl_loss=True \
    actor_rollout_ref.actor.kl_loss_coef=0.001 \
    actor_rollout_ref.actor.kl_loss_type=low_var_kl \
    actor_rollout_ref.actor.entropy_coeff=0 \
    actor_rollout_ref.rollout.log_prob_micro_batch_size_per_gpu=1 \
    actor_rollout_ref.rollout.tensor_model_parallel_size=$tp \
    actor_rollout_ref.rollout.name=vllm \
    actor_rollout_ref.rollout.gpu_memory_utilization=0.6 \
    actor_rollout_ref.rollout.n=8 \
    actor_rollout_ref.ref.log_prob_micro_batch_size_per_gpu=1 \
    actor_rollout_ref.ref.megatron.pipeline_model_parallel_size=$pp \
    actor_rollout_ref.ref.megatron.tensor_model_parallel_size=$tp \
    actor_rollout_ref.ref.megatron.expert_model_parallel_size=$ep \
    actor_rollout_ref.ref.megatron.use_dist_checkpointing=True \
    actor_rollout_ref.ref.megatron.dist_checkpointing_path=$DIST_CKPT_PATH \
    algorithm.use_kl_in_reward=False \
    trainer.critic_warmup=0 \
    trainer.logger=['console'] \
    trainer.project_name='verl_grpo_example_gsm8k_math_base' \
    trainer.experiment_name='qwen3_30b_moe_megatron_base' \
    trainer.n_gpus_per_node=16 \
    trainer.nnodes=2 \
    trainer.save_freq=20 \
    trainer.default_local_dir=/data/checkpoints/verl_grpo_example_gsm8k_math_base/qwen3_30b_moe_megatron_base \
    trainer.test_freq=20 \
    trainer.total_epochs=10 \
    actor_rollout_ref.ref.megatron.expert_tensor_parallel_size=$etp \
    actor_rollout_ref.actor.megatron.expert_tensor_parallel_size=$etp \
    +actor_rollout_ref.actor.megatron.override_transformer_config.recompute_method=uniform \
    +actor_rollout_ref.actor.megatron.override_transformer_config.recompute_granularity=full \
    +actor_rollout_ref.actor.megatron.override_transformer_config.recompute_num_layers=1 \
    actor_rollout_ref.actor.megatron.context_parallel_size=$cp \
    actor_rollout_ref.ref.megatron.param_offload=True \
    actor_rollout_ref.actor.megatron.param_offload=True \
    actor_rollout_ref.actor.megatron.optimizer_offload=True \
    actor_rollout_ref.actor.megatron.grad_offload=True \
    trainer.device=npu \
    +actor_rollout_ref.actor.megatron.override_transformer_config.use_flash_attn=True \
    +actor_rollout_ref.actor.megatron.override_transformer_config.use_distributed_optimizer=True \
    +actor_rollout_ref.actor.megatron.override_transformer_config.sequence_parallel=True \
    +actor_rollout_ref.actor.megatron.override_transformer_config.context_parallel_size=$cp
